[package]
name = "nexus"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
path = "src/native/lib.rs"

[dependencies]
jni = "0.21.1"
vulkano = "0.35.2"
ash = "0.38.0+1.3.281" 
anyhow = "1.0.100"

[profile.dev]
opt-level = 1 
